const CompanyAddressRoutes = require('./companyAddressRoutes');
const CompanyBannerRoutes = require('./companyBannerRoutes');
const CompanyEmailRoutes = require('./companyEmailRoutes');
const CompanyPhoneRoutes = require('./companyPhoneRoutes');
const CompanySocialMediaRoutes = require('./companySocialMediaRoutes');
const ManufacturerBrandRoutes = require('./manufacturerBrandRoutes');
const VehicleClassificationRoutes = require('./vehicleClassificationRoutes');
const VehiclePhotoRoutes = require('./vehiclePhotoRoutes');
const UserVehicleRatingRoutes = require('./userVehicleRatingRoutes');
const VehicleItemRoutes = require('./vehicleItemRoutes');
const VehicleRoutes = require('./vehicleRoutes');
const VehicleGearRoutes = require('./vehicleGearRoutes');
const VehicleFuelRoutes = require('./vehicleFuelRoutes');
const FuelRoutes = require('./fuelRoutes');
const UserVehicleProposalRoutes = require('./userVehicleProposalRoutes');
const ManufacturerBrandVersionRoutes = require('./manufacturerBrandVersionRoutes');
const VehicleConditionRoutes = require('./vehicleConditionRoutes');
const VehicleTransmissionTypeRoutes = require('./vehicleTransmissionTypeRoutes');
const UserRoutes = require('./userRoutes');

module.exports = (app) => {
  app.use(`/api/${CompanyAddressRoutes.modelName}`, CompanyAddressRoutes);
  app.use(`/api/${CompanyBannerRoutes.modelName}`, CompanyBannerRoutes);
  app.use(`/api/${CompanyEmailRoutes.modelName}`, CompanyEmailRoutes);
  app.use(`/api/${CompanyPhoneRoutes.modelName}`, CompanyPhoneRoutes);
  app.use(`/api/${CompanySocialMediaRoutes.modelName}`, CompanySocialMediaRoutes);
  app.use(`/api/${ManufacturerBrandRoutes.modelName}`, ManufacturerBrandRoutes);
  app.use(`/api/${VehicleClassificationRoutes.modelName}`, VehicleClassificationRoutes);
  app.use(`/api/${VehiclePhotoRoutes.modelName}`, VehiclePhotoRoutes);
  app.use(`/api/${UserVehicleRatingRoutes.modelName}`, UserVehicleRatingRoutes);
  app.use(`/api/${VehicleItemRoutes.modelName}`, VehicleItemRoutes);
  app.use(`/api/${VehicleRoutes.modelName}`, VehicleRoutes);
  app.use(`/api/${VehicleGearRoutes.modelName}`, VehicleGearRoutes);
  app.use(`/api/${VehicleFuelRoutes.modelName}`, VehicleFuelRoutes);
  app.use(`/api/${FuelRoutes.modelName}`, FuelRoutes);
  app.use(`/api/${UserVehicleProposalRoutes.modelName}`, UserVehicleProposalRoutes);
  app.use(`/api/${ManufacturerBrandVersionRoutes.modelName}`, ManufacturerBrandVersionRoutes);
  app.use(`/api/${VehicleConditionRoutes.modelName}`, VehicleConditionRoutes);
  app.use(`/api/${VehicleTransmissionTypeRoutes.modelName}`, VehicleTransmissionTypeRoutes);
  app.use(`/api/${UserRoutes.modelName}`, UserRoutes);
};