console.log(process.env.MYSQL_USER)
console.log(process.env.MYSQL_PASSWORD)
console.log(process.env.MYSQL_DATABASE)
console.log(process.env.MYSQL_HOST)
console.log(process.env.MYSQL_PORT)
console.log(process.env)